name: Set up the project
description: Install uv, Python, and the project dependencies
runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        version: "0.4.10"

    - run: uv python install 3.10
      shell: bash

    - run: uv sync --locked
      shell: bash
